# Defining Ruby version(s)
language: ruby
rvm:
  - 2.5.1
# Third party services
services:
  - postgresql
# Caching
cache:
  # Caching dependencies: need to refer to directories as install step is
  # overridden: 
  # https://docs.travis-ci.com/user/caching/#caching-and-overriding-install-step
  directories:
    - vendor/bundle

env:
  global:
    # CC_TEST_REPORTER_ID defined in environment variables

# Dependencies
before_install:
  # Code Climate: initialization
  # note: simplecov and simplecov-console gems required
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# Dependencies installation
install:
  - bundle install --path vendor/bundle

# Script definition
before_script:
  - psql -c 'CREATE DATABASE learn_rails_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - rspec

after_script:
  # Code Climate: sending report
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
notifications:
  slack:
    rooms:
      secure: s7Ih9EdHnmv540ScoYw2ZqhxPb90xXSEP0rabgrqw9hQ69EjH7H8SLVRrC7R6K+jRT7Rh38W6EM+jU3u9cPav4ENG9sILL5D+KWrvfKaEhcpBP03Ax7X4PMLOsIR/IU+35tCxgQWuSt96Uh8G+jSt3XSKzbphUABfDGGnNjwovOiPok9E2OzGFAXqJ4U/gY+KlTU6uIdKovsPYRArEnc6KtxxPN5+m3LjcMP1grpTFOw60WZ5Q3WAYwr/SE0wQbIoS4p7YOaLw6GNVh5HQsuziM8v5veciLFGY15uw5NCzx/OhqlRJuIlpJvk6zXDkHtY0pm4WKW7yF6wiMxV2X7Wvsm7+hYUpyigu5sQeFKgWBooZeJajqyb66Tmb/nbj3ltIk+B3yW8IK9VW+Gv42dkHqgqJAs9U935FUZufa09COKGU0AaofqX9zvcUefGDqRWXsP8SZucixd5AIw4220kSKB0pZIhYpXE2GBH/U87YXyblciGkey955I82Soy4Pdn5O2Tra8qt8m2s1T8gr0gf/F6ZzcWHIfIVev/f0zwNc+4y9SEeK6hQQSBHY0F9UhpqnBjB22rp7H9Ae3/xAVUD+kQwy3qVD7+XsDZ/XbtY7mdEj2ci1Bbh9/nobMJQEGmev7BuXvjHbTsg0WYf6TphnAEV1FICTMV421pubXsyg=
    on_success: always
    on_failure: always
