version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - build

jobs:
  build:
    docker:
      # >> https://hub.docker.com/r/circleci/ruby/
      - image: circleci/ruby:2.6.0
    working_directory: ~/repo

    steps:
      - checkout

      # === Dependencies ===
      - restore_cache:
          keys:
            - learn-rails-dependencies-{{ checksum "Gemfile.lock" }}
            - learn-rails-dependencies-
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: learn-rails-dependencies-{{ checksum "Gemfile.lock" }}